apiVersion: v1
kind: Namespace
metadata:
  name: cert-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: "^1"
  targetNamespace: cert-system
  valuesContent: |-
    installCRDs: true
