apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  version: "^1"
  targetNamespace: kube-system
  valuesContent: |-
    encryption:
      # See https://docs.cilium.io/en/stable/gettingstarted/encryption-wireguard/
      enabled: true
      type: wireguard
    l7Proxy: false
