apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: fluxcd
  namespace: kube-system
spec:
  repo: https://fluxcd-community.github.io/helm-charts
  chart: flux2
  version: "^1"
  targetNamespace: flux-system
