apiVersion: v1
kind: Namespace
metadata:
  name: o11y-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: "^40"
  targetNamespace: o11y-system
