apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluxcd-community
  namespace: flux-system
spec:
  interval: 5m
  url: https://fluxcd-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: flux2
      version: "^1"
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
        namespace: flux-system
