- name: Clear known host entries
  hosts: localhost
  tasks:
    - name: Clear all cluster hosts from known_hosts file
      with_items: "{{ groups['k8s_cluster'] }}"
      ansible.builtin.command: "ssh-keygen -f $HOME/.ssh/known_hosts -R {{ hostvars[item].ansible_host }}"
