apiVersion: v1
kind: Namespace
metadata:
  name: backup-system
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  labels:
      velero.io/csi-volumesnapshot-class: "true"
  name: longhorn
  namespace: backup-system
driver: driver.longhorn.io
deletionPolicy: Delete
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-credentials
  namespace: backup-system
type: Opaque
data:
  cloud: {{ printf "[default]\naws_access_key_id=%s\naws_secret_access_key=%s" .Values.s3_backup.access_key.id .Values.s3_backup.access_key.secret | b64enc }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vmware-tanzu
  namespace: flux-system
spec:
  interval: 1h
  url: https://vmware-tanzu.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: backup-system
spec:
  interval: 1h
  chart:
    spec:
      chart: velero
      version: "^2"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    {{ .Files.Get "bootstrap-values/velero.yaml" | nindent 4 }}
    configuration:
      backupStorageLocation:
        name: default
        bucket: {{ .Values.s3_backup.bucket }}
        prefix: velero
        config:
          region: {{ .Values.s3_backup.region }}
          s3Url: {{ printf "https://%s" .Values.s3_backup.endpoint }}
      volumeSnapshotLocation:
        name: default
        config:
          region: {{ .Values.s3_backup.region }}
