apiVersion: v1
kind: Namespace
metadata:
  name: backup-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/kubernetes-csi/external-snapshotter
  ref:
    branch: release-6.1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: volume-snapshot-crds
  namespace: backup-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  path: "./client/config/crd"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: volume-snapshot-controller
  namespace: backup-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  path: "./deploy/kubernetes/snapshot-controller"
  prune: true
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  labels:
      velero.io/csi-volumesnapshot-class: "true"
  name: longhorn
  namespace: backup-system
driver: driver.longhorn.io
deletionPolicy: Delete
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-credentials
  namespace: backup-system
type: Opaque
data:
  cloud: {{ printf "[default]\naws_access_key_id=%s\naws_secret_access_key=%s" .Values.s3_backup.access_key.id .Values.s3_backup.access_key.secret | b64enc }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vmware-tanzu
  namespace: flux-system
spec:
  interval: 1h
  url: https://vmware-tanzu.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: backup-system
spec:
  interval: 1h
  chart:
    spec:
      chart: velero
      version: "^2"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    credentials:
      existingSecret: s3-backup-credentials
    initContainers:
      - name: velero-plugin-for-csi
        image: velero/velero-plugin-for-csi:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    snapshotsEnabled: true
    configuration:
      provider: aws
      features: EnableCSI
      backupStorageLocation:
        name: default
        bucket: {{ .Values.s3_backup.bucket }}
        prefix: velero
        config:
          region: {{ .Values.s3_backup.region }}
          s3Url: {{ printf "https://%s" .Values.s3_backup.endpoint }}
      volumeSnapshotLocation:
        name: default
        config:
          region: {{ .Values.s3_backup.region }}
    schedules:
      full-backup:
        disabled: false
        schedule: "0 0 * * *"
        useOwnerReferencesInBackup: false
        template:
          includedNamespaces:
            - "*"
          includeClusterResources: true
          snapshotVolumes: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
