apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluxcd-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://fluxcd-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: flux2
      version: "^1"
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    {{ .Files.Get "bootstrap-values/fluxcd.yaml" | nindent 4 }}
    prometheus:
      podMonitor:
        create: true
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-auth
  namespace: flux-system
type: Opaque
data:
  issuerURL: {{ printf "https://%s" (include "get_hostname" (dict "service" "dex" "context" $)) | b64enc }}
  clientID: {{ "admin-oidc" | b64enc }}
  clientSecret: {{ .Values.clusterSecret | b64enc }}
  redirectURL: {{ printf "https://%s/oauth2/callback" (include "get_hostname" (dict "service" "weave_gitops" "context" $)) | b64enc }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
  interval: 1h
  timeout: '20m0s' # Setting up public domains for OIDC takes time.
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
        {{ include "admin_auth_annotations" . | nindent 8 }}
      hosts:
        - host: {{ include "get_hostname" (dict "service" "weave_gitops" "context" $) }}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: weave-gitops-tls
          hosts:
            - {{ include "get_hostname" (dict "service" "weave_gitops" "context" $) }}
    metrics:
      enabled: false
    adminUser:
      create: true
      username: admin
      passwordHash: {{ htpasswd "admin" .Values.clusterSecret }}
