---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "^1"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    {{ .Files.Get "bootstrap-values/cilium.yaml" | nindent 4 }}
    hubble:
      # See https://docs.cilium.io/en/stable/gettingstarted/hubble_setup/
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - icmp
        serviceMonitor:
          enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: acme
            {{ include "admin_auth_annotations" . | nindent 12 }}
          hosts: 
            - {{ include "get_hostname" (dict "service" "cilium_ui" "context" $) }}
          tls:
            - hosts:
                - {{ include "get_hostname" (dict "service" "cilium_ui" "context" $) }}
              secretName: cilium-tls
