apiVersion: v2
name: k8s-baseline
description: Infrastructure chart to supply baseline k8s infrastructure
type: application
version: "0.0.1"
appVersion: "1.0"
dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
